# -*- coding: utf-8 -*-
"""Calcular el area de un circulo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDo4HDw4j_x3aINKhBiHf0mZ2HY0TZ-v
"""

import math

# 1. Ingresar el radio
radio = float(input("Ingrese el radio del círculo: "))

# 2. Calcular el área
area = math.pi * (radio ** 2)

# 3. Imprimir el valor del área
print("El área del círculo es:", area)